# Generated by Django 4.1.7 on 2023-05-09 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Rider', 'Rider')], max_length=100, null=True)),
                ('full_name', models.CharField(max_length=300)),
                ('picture', models.FileField(upload_to='static')),
                ('zip_code', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('favourite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='fav_prod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
