# Generated by Django 3.2.18 on 2024-05-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
        ('Cart', '0002_alter_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='UserAccount.users', verbose_name='Customer'),
        ),
    ]
