# Generated by Django 5.1.3 on 2025-04-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0004_coupon_is_expired_alter_cart_coupon_and_more"),
        ("Products", "0005_remove_productvariations_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="Prod_Var",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.productvariant",
                verbose_name="prod_variant",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="Cart.cart",
            ),
        ),
    ]
