# Generated by Django 5.1.3 on 2025-04-12 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0005_alter_cartitem_prod_var_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="Prod_Var",
            new_name="product_variant",
        ),
    ]
