# Generated by Django 5.1.3 on 2025-04-13 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0006_rename_prod_var_cartitem_product_variant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart"},
        ),
    ]
