# Generated by Django 3.2.4 on 2025-07-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_alter_cart_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Total_Price',
            new_name='total_price',
        ),
    ]
