# Generated by Django 4.1.7 on 2023-05-09 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccount', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('delivery_option', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], default='COD', max_length=100)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Preparing', 'Preparing'), ('Shipping', 'Shipping'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Created', max_length=100)),
                ('adminnote', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('placed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.users', verbose_name='Customer_Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Prod_Var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productvariations', verbose_name='Prod_Var_Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='OrderItem_order')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('request', models.CharField(choices=[('Refund', 'Refund'), ('Exchange the Product', 'Exchange the Product')], max_length=50)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('Prod_Var', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.productvariations', verbose_name='prod_var_complain')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='complain_order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
