# Generated by Django 4.1.7 on 2023-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_subscription_email_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled')], default='Active', max_length=100),
        ),
    ]
