# Generated by Django 5.1.3 on 2025-04-02 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders", "0004_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
