# Generated by Django 5.1.3 on 2025-04-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0004_coupon_is_expired_alter_cart_coupon_and_more"),
        ("Orders", "0005_alter_order_order_id"),
        ("UserAccount", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="adminnote",
            new_name="admin_note",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_cart",
                to="Cart.cart",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserAccount.users",
                verbose_name="customer",
            ),
        ),
    ]
