# Generated by Django 5.1.3 on 2025-04-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders", "0006_rename_adminnote_order_admin_note_order_cart_and_more"),
        ("Products", "0005_remove_productvariations_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complain",
            name="Prod_Var",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="Products.productvariant",
                verbose_name="prod_var_complain",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="Prod_Var",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant",
                to="Products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="Orders.order",
            ),
        ),
    ]
