# Generated by Django 5.1.3 on 2025-04-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_complain_prod_var_alter_orderitem_prod_var_and_more'),
        ('Products', '0007_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Prod_Var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_complain', to='Products.productvariant'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='complain'),
        ),
    ]
