# Generated by Django 5.1.3 on 2025-04-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders", "0008_alter_complain_prod_var_alter_complain_order"),
        ("UserAccount", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complain",
            old_name="Prod_Var",
            new_name="product_variant",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="Prod_Var",
            new_name="product_variant",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="UserAccount.users",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("OP", "Online Payment")],
                default="COD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
