# Generated by Django 3.2.4 on 2025-04-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_rename_prod_var_complain_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(auto_now=True),
        ),
    ]
