global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-ecommerce'
#    metrics_path: '/home'
    static_configs:
      - targets: ['ecommerce-backend:8000']
