# Generated by Django 4.1.7 on 2023-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_reviews_product_alter_reviews_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Image',
            field=models.FileField(null=True, upload_to='static'),
        ),
    ]
