# Generated by Django 4.1.7 on 2023-05-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
