# Generated by Django 5.1.3 on 2025-04-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0004_alter_variationvalue_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariations",
            name="images",
        ),
        migrations.RemoveField(
            model_name="productvariations",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productvariations",
            name="variation",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product_variation",
        ),
        migrations.AlterField(
            model_name="variationvalue",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="value",
                to="Products.variation",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=150, null=True)),
                ("price", models.IntegerField()),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="Products.product",
                    ),
                ),
                (
                    "variation",
                    models.ManyToManyField(
                        related_name="variations", to="Products.variationvalue"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productimage",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="Products.productvariant",
            ),
        ),
    ]
