# Generated by Django 5.1.3 on 2025-04-07 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0005_alter_cartitem_prod_var_alter_cartitem_cart"),
        ("Orders", "0007_alter_complain_prod_var_alter_orderitem_prod_var_and_more"),
        ("Products", "0005_remove_productvariations_images_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariations",
        ),
    ]
