# Generated by Django 5.1.3 on 2025-04-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0007_alter_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="name",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
