# Generated by Django 5.1.3 on 2025-04-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0008_alter_variation_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="reviewimages",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Products.reviews",
                verbose_name="review_images",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="Products.product",
                verbose_name="product_reviews",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
